### PR TITLE
fix #33 allow html in captions

### LINKED ISSUE #33: Captions strip out HTML
I didn't even know that WordPress supported HTML within captions, but since it does we should probably stop using `.text` in favor of `.html`.

### PR DESCRIPTION
**Pull request by michakrapp**

### CODE REVIEW

**Comment by michakrapp** [comment]
Only changed unminified file

**Comment by michakrapp** [comment]
Thanks for merge.
Looking forward for the plugin update release

**Comment by michakrapp** [comment]
Any news when the plugin update will come?

**Comment by robneu** [comment]
https://www.youtube.com/watch?v=wEBlaMOmKV4

**Pull request merged**
